<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AOVPN.Controller</AssemblyName>
    <RootNamespace>AOVPN.Controller</RootNamespace>
  </PropertyGroup>
</Project>
